title: Taipei Hackerspace
description: ""
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://test-taipeihack.github.io" # change this to the base hostname & protocol for your site


google_analytics: "UA-131051587-5"

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Taipei Hackerspace
image: /logo/jpg/hackerspace500.jpg
twitter:
  username: "taipeihack"

plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
target-blank:
    rel: nofollow

header_page_refs: ['wiki','hs-en','hs-cn']
